### ISSUE TITLE
Support from Structured Outputs/JSON mode

### ISSUE THREAD

**Issue by kyranb** [echolabsdev/prism#11]
It would be great to support the `response_format` option that some providers expose to create structured outputs.

https://platform.openai.com/docs/api-reference/chat/create

https://platform.openai.com/docs/guides/structured-outputs

**Comment by balu-lt** [comment]
You can find a list of upcoming features in the [roadmap](https://prism.echolabs.dev/roadmap.html).

**Comment by sixlive** [comment]
Thanks @balu-lt!
