### ISSUE TITLE
code-interpreter?

### ISSUE THREAD

**Issue by FrankFlow** [echolabsdev/prism#12]
I can't see how to turn on code-interpreter?
Thansk a lot

**Comment by sixlive** [comment]
I'll look into this!

**Comment by sixlive** [comment]
I don't have immediate plans to support this as it's exclusive to OpenAI and I haven't quite sorted out how I want to expose provider specific features. This may be something I revisit in the future. You can probably figure out how to do this via a custom provider in the mean time.
