### ISSUE TITLE
Groq text generation

### ISSUE THREAD

**Issue by pushpak1300** [echolabsdev/prism#14]
Are you open to add groq support ? If Yes I can work on it https://console.groq.com/docs/quickstart

**Comment by sixlive** [comment]
Yeah! Totally open to it! Looking forward to the PR!

**Comment by sixlive** [comment]
I'll be re-working drivers and providers, tracking via https://github.com/echolabsdev/prism/issues/19

**Comment by sixlive** [comment]
Was this meant for Groq or Grok lol

**Comment by pushpak1300** [comment]
Groq. 🤣
