### ISSUE TITLE
Support for `object` and `array` types in Tool params.

### ISSUE THREAD

**Issue by slashequip** [echolabsdev/prism#15]
OpenAI (and others I believe) allow you to us `object` and `array` types for Tool params. They require additional fields to build the param data, for example;

```
'tags' => [
    'type' => 'array',
    'items' => [
        'type' => 'string',
        'description' => 'Tags or categories for the recipe',
    ],
],
```

```
'nutrition' => [
    'type' => 'object',
    'properties' => [
        'calories' => [
            'type' => 'integer',
            'description' => 'Calories per serving',
        ],
        'fat' => [
            'type' => 'number',
            'description' => 'Fat content in grams per serving',
        ],
        'carbs' => [
            'type' => 'number',
            'description' => 'Carbohydrate content in grams per serving',
        ],
        'protein' => [
            'type' => 'number',
            'description' => 'Protein content in grams per serving',
        ],
    ],
],
```

It might be helpful to consider the building of ValueObjects for params in the future, this could make it easier to define the params without a large list of args to the `withParameter` method.

**Comment by sixlive** [comment]
I had been thinking about this but wanted to focus getting basic support in place. This is something I want to tackle soon! I was also thinking about creating a set of value objects to make things a little cleaner.

**Comment by slashequip** [comment]
Yup, I get it! :) 

It's the one thing stopping me from switching from my own messy logic to Prism, as all my tools have nested items.

From what I've played with so far it's looking like a really dope package though 👌

**Comment by sixlive** [comment]
I've started digging into this, hoping to have an initial PR by the end of the week.

**Comment by slashequip** [comment]
Don't tease me now.

**Comment by sixlive** [comment]
What do you think about something like this

```php
Tool::as('tool')
    ->for('useful for nothing')
    ->withString(name: 'query', description: 'the search query', required: false)
    ->withBoolean('active', 'active status')
    ->withArray(
        'items',
        'user requested items',
        'string',
        'the items in the basket',
    )
    ->withObject(
        'user',
        'the user object',
        [
            new StringParameter('name', 'the users name'),
            new BooleanParameter('active_status', 'user active status'),
        ],
        [
            'name',
        ]
    );
```

**Comment by slashequip** [comment]
Moving in the right direction for sure, few _opinions_ from me.

IMO leaning more on the value objects would be nicer - `withArray` would move to 3 args then and be a little cleaner

Implementing the above would allow you to easily configure arrays of objects by introducing an `ObjectParameter` value object.


```
->withArray(
    name: 'ingredients',
    item: new ObjectParameter(
        new StringParameter('name', 'name of the ingredient'),
        new IntegerParameter('qty', 'quantity of ingredient'),
        new EnumParameter('qty_type', 'the type of the quantity', ['grams', 'cups']),
    ),
)
```

If parameter value objects allowed you to defined required or not then you could pull that from those rather than hand typing them in the `withObject` method.

Initially the naming was a little jarring to me, perhaps a little confusing, but now I've chewed on it before writing this for a few hours it's ok now.

You could also leave `withParameter` that accepts a value object as the only arg which would give several paths to defining a tool.

Hope some of those opinions help!

**Comment by sixlive** [comment]
Hey! Thanks for a ll the feedback. I actually made some of those changes this morning after sleeping on it.

Array now accepts a `Parameter` object for defining items (https://github.com/echolabsdev/prism/pull/25/commits/53c207c84645d48b9c5fa459067e1902f48988fe).

The `withParameter` method remains and accepts a `Parameter` object! That way if you wanted to create a more complex parameter you can do that separately and pass it in.

```php
$schema = new ObjectParameter(
    name: 'user',
    description: 'a user object',
    properties: [
        new StringParameter('name', 'the users name'),
        new NumberParameter('age', 'the users age'),
        new EnumParameter(
            name: 'status',
            description: 'the users status',
            options: [
                'active',
                'inactive',
                'suspended',
            ]
        ),
        new ArrayParameter(
            name: 'hobbies',
            description: 'the users hobbies',
            item: new StringParameter('hobby', 'the users hobby')
        ),
        new ObjectParameter(
            name: 'address',
            description: 'the users address',
            properties: [
                new StringParameter('street', 'the street part of the address'),
                new StringParameter('city', 'the city part of the address'),
                new StringParameter('country', 'the country part of the address'),
                new NumberParameter('zip', 'the zip code part of the address'),
            ]
        ),
    ]
);

Tool::as('create user')
    ->withParameter($schema)
    // ...
```

Honestly, the naming does feel a little awkward, I might rename them to `->withStringParameter`, `->withObjectParameter`, etc. or maybe even `->withStringParam()`, `->withObjectParam`... I don't know, "parameter" just feels like a mouth full haha.

**Comment by slashequip** [comment]
Awesome.

`with****Parameter` makes more sense, a mouthful yes, but we have IDEs right, never need to type that 🤞 

Love where this has got to, from what I can see that checks the boxes for my needs, which I think I complex enough currently. This gives us lots of flexibility.

**Comment by sixlive** [comment]
Merged! I updated the docs with the final functionality! https://prism.echolabs.dev/tool-calling.html#defining-parameters

**Comment by slashequip** [comment]
Amazing! Going to work on replacing my homegrown stuff with Prism tonight now as it should check all the boxes. I'll be sure to bring any feedback your way.

Going to save me a bunch of LOC as it handles all the tool calls and everything. Appreciate you getting this done!
