### ISSUE TITLE
Support for adding images for models that support it

### ISSUE THREAD

**Issue by yoavf** [echolabsdev/prism#17]
Some of the models accept images (and possibly other media) as input for text generation. 

How should this be implemented? 
How would drivers declare support for this?

**Comment by sixlive** [comment]
Its definitely something I want to support. I've got an item on the [roadmap](https://prism.echolabs.dev/roadmap.html#short-term-goals). Initially, I'll be looking to the Vercel SDK ([ref](https://sdk.vercel.ai/docs/foundations/prompts#image-parts)) and probably looking to implement something similar.

**Comment by sixlive** [comment]
Tracking via https://github.com/echolabsdev/prism/issues/28
