### ISSUE TITLE
Would setting a default model be helpful from the config?

### ISSUE THREAD

**Issue by peterramsing** [echolabsdev/prism#18]
Would it be helpful to have default model in the config:
```php
'openai' => [
    'driver' => 'openai',
    'url' => env('OPENAI_URL', 'https://api.openai.com/v1'),
    'api_key' => env('OPENAI_API_KEY'),
    'default_model' => 'gpt-4o-mini-2024-07-18' #default
],
```

In addition, one thing that I do when working on packages for clients is that I will enforce a pinned version (so no usage of `latest` or `4o-mini` without the pin so that they don't see changes in their app over time as the models move. I could see there being a strict mode that could be configured.
```php
'openai' => [
    'driver' => 'openai',
    'url' => env('OPENAI_URL', 'https://api.openai.com/v1'),
    'api_key' => env('OPENAI_API_KEY'),
    'strict' => true #whether to allow non-pinned models
],
```

**Comment by sixlive** [comment]
Interesting idea, going to pass on it for now though.
