### ISSUE TITLE
Refactor drivers and providers 

### ISSUE THREAD

**Issue by sixlive** [echolabsdev/prism#19]
## Description

After further consideration, we need to move away from multi-use drivers. It's becoming apparent that providers like Mistral, Ollama, and Grok may struggle to keep pace with the rapid changes in OpenAI's API contract.

**Proposed Changes:**

- Implement a 1:1 driver → provider model
- Create an OpenAIAPI base driver or a collection of traits to handle overlapping driver functionality
- Rework the existing system to accommodate these changes
- Implement the Ollama driver as a use case for the new model

**Comment by pushpak1300** [comment]
@sixlive I really like approach to use specific driver the way vercel ai sdk or langchain uses.
For eg. will need have implementation for all the drivers. So feature extending will be easy if one driver support and another driver doesn't support it.

**Comment by sixlive** [comment]
Yeah, I've gone back and forth on this.

```php
Prism::text()
  ->using(new OpenAI('gpt-4'))
  ->prompt('Introduce yourself')
```

or

```php
Prism::text()
  ->using('openai', 'gpt-4')
  ->prompt('Introduce yourself')
```

**Comment by petervandijck** [comment]
Just syntax-wise this seems cleanest to me (just one person's very subjective opinion).

`Prism::text()
  ->using('openai', 'gpt-4')
  ->prompt('Introduce yourself')`
