### ISSUE TITLE
Required tools

### ISSUE THREAD

**Issue by sixlive** [echolabsdev/prism#21]
We should allow for required tools, meaning the model is required to use a specific tool.

**Comment by mattglover11** [comment]
hey @sixlive I'd be happy to work on this one if you like if you don't already have it covered - I have an immediate need for it ;)

**Comment by sixlive** [comment]
Really appreciate the offer! I've got a few ideas / opinions around handling this. My goal is to tackle it this week/weekend. I'll be sure to reach out for some feedback from you before I merge!
