### ISSUE TITLE
Support for Vision

### ISSUE THREAD

**Issue by slashequip** [echolabsdev/prism#32]
Current we cannot send user messages that are image URLs or base64 encodes, as outlined in OpenAI's Vision docs;

https://platform.openai.com/docs/guides/vision

I'd expect this could be an easy one to to add, we'd just need a new Message type, and adjusting the message maps appropriately to build the correct payload.

**Comment by slashequip** [comment]
I'll spin up a PR for this and see how far I can get it :)

**Comment by sixlive** [comment]
I'm definitely interested in this, its on the [short-term roadmap](https://prism.echolabs.dev/roadmap.html#short-term-goals)
