### ISSUE TITLE
failed: cURL error 28: Operation timed out after 30001 milliseconds with 0 bytes received

### ISSUE THREAD

**Issue by mh97m** [echolabsdev/prism#33]
how to increase curl timeout when using ollama provider??
`$response = Prism::text()
        ->using(Provider::Ollama, 'qwen2')
        ->withMessages([
            new UserMessage('Hello, who are you?'),
            new AssistantMessage('I am an AI assistant created by Anthropic. How can I help you today?'),
            new UserMessage('Can you tell me about the weather in Paris?'),
        ])
        ->generate();`. and can we do not use curl when using ollama locally?

**Comment by sixlive** [comment]
I'll get something put together for exposing client options this weekend!

**Comment by sixlive** [comment]
I just tagged [v0.6.0](https://github.com/echolabsdev/prism/releases/tag/v0.6.0) with support for a `->withClientOptions()` method for additional client configurations. 

```php
Prism::text()
  ->using(Provider::Ollama, 'qwen2.5')
  ->withClientOptions(['timeout' => '20'])
  ->withPrompt('Who are you?')
  ->generate();
  ```
  
  The method accepts any of [Guzzle's request options](https://docs.guzzlephp.org/en/stable/request-options.html).

**Comment by mh97m** [comment]
awesome :)
