### ISSUE TITLE
Exception improvement

### ISSUE THREAD

**Issue by slashequip** [echolabsdev/prism#39]
I think the below error could be caught and improved to make it a little more clear as to what the issue is.

![SCR-20241022-jhht](https://github.com/user-attachments/assets/8c61b252-d734-4ae4-a1a2-cf64984367d0)

It results from you defining a Tool with expected parameters and then not including those args in your callable (in my case an `__invoke` method).

Caught me out a few times now when adjusting the Tool parameters and not accounting for them in the handling. The exception makes sense, I think it could be caught and transformed into something more helpful.

**Comment by sixlive** [comment]
Love this idea. Will get something merged in this week!

**Comment by pushpak1300** [comment]
@sixlive if you're occupied with the other stuff. I can actually work with this along with #14 ? 
Any specific implement you're planning ?

**Comment by sixlive** [comment]
@pushpak1300 That would be awesome, I'm working on image support at the moment.

I was probably just going to wrap it in a try/catch or use the rescue helper and add a custom method to the PrismException class with more details. Should be pretty straightforward.
