### ISSUE TITLE
Gemini text completions

### ISSUE THREAD

**Issue by sixlive** [echolabsdev/prism#4]
## Description

Create a new driver for Gemini and add it to the default config

https://ai.google.dev/gemini-api/docs

**Comment by sarfraznawaz2005** [comment]
Adding Gemini will be extremely useful because that's what most people are using because of it's great free tier.

**Comment by crissto** [comment]
Hey! Nice work on the package! Interested in this issue. Would it be ok to use a dependency like https://github.com/gemini-api-php/client? If this is an option, happy to work on a PR soon.

**Comment by yoavf** [comment]
@crissto if you haven't already started working on this - I'm almost done. Since I didn't comment here before, no worries if you've already started :)

**Comment by sixlive** [comment]
Yall, this is awesome. 

I'd really prefer if we use the Laravel's HTTP helper and roll our own clients, makes testing MUCH easier.

**Comment by crissto** [comment]
> @crissto if you haven't already started working on this - I'm almost done. Since I didn't comment here before, no worries if you've already started :)

No worries, I haven't started. Thanks for the help. Wanted to build it to use it actually. So you thanks!!

**Comment by pushpak1300** [comment]
If this is something now one is working I can star working on this next @sixlive

**Comment by sixlive** [comment]
@pushpak1300 that would be 🤩 AMAZING

**Comment by sarfraznawaz2005** [comment]
> @sixlive while working on this I came across post where Gemini now start supporting OpenAI API. Should we build the integration with Gemini OpenAI API or Normal Gemini api ?
> 
> https://t.co/fG2f6EFsFY

> If you aren't already using the OpenAI libraries, we recommend that you call the [Gemini API directly](https://ai.google.dev/gemini-api/docs/quickstart).

Ref: https://ai.google.dev/gemini-api/docs/openai

You never know they can stop supporting OpenAI, using gemini own api will be better as it will always be uptodate unlike openai support which will always be few steps back in terms of latest work done on gemini.

@sixlive can suggest better though.

**Comment by sixlive** [comment]
I just took a look at it, it's probably worth it to use the Gemini API rather than their OpenAI compatibility layer.

**Comment by sawirricardo** [comment]
any updates on this?

**Comment by pushpak1300** [comment]
@sawirricardo https://x.com/pushpak1300/status/1863481293604098209 will try to wrap up this by next week.

**Comment by sawirricardo** [comment]
very noiicee @pushpak1300

**Comment by polbatllo** [comment]
I guess no news on this, right?

**Comment by sarfraznawaz2005** [comment]
Please also update docs for Gemini. Thanks
