### ISSUE TITLE
Bug: Prism generate() returns empty text when using custom tool

### ISSUE THREAD

**Issue by LonnyX** [echolabsdev/prism#41]
## Issue Description

When using a custom tool with Prism's `generate()` 

## Steps to Reproduce

1. Create a new test in `tests/Feature/PrismTest.php`:

```php:tests/Feature/PrismTest.php
public function test_prism_with_weather_tool(): void
{
    $weatherTool = Tool::as('weather')
        ->for('Get current weather conditions')
        ->withStringParameter('city', 'The city to get weather for')
        ->using(function (string $city) {
            return "The weather in {$city} is sunny and 72°F.";
        });

    $prism = Prism::text()
        ->using('openai', 'gpt-4o-mini')
        ->withPrompt("What's the weather like in Paris today? Should I bring a coat?")
        ->withTools([$weatherTool])
        ->withMaxSteps(1);

    $response = $prism->generate();

    $this->assertNotEmpty($response->text);
}
```

2. Run the test.

## Expected Behavior

The `$response->text` should contain a non-empty string with a generated response that incorporates the weather information for Paris.

## Additional Context

- Laravel Version 11.29.0  
- PHP Version 8.3.12
- Prism Package Version: v0.6.0

**Comment by LonnyX** [comment]
it looks like the `withMaxSteps()` should be more than 1

**Comment by sixlive** [comment]
> it looks like the `withMaxSteps()` should be more than 1

Looks like you figured it out while I was typing up my response!

**Comment by LonnyX** [comment]
Thank you for your response.

I had a different understanding of how Prism would handle tool results. My initial assumption was that when using a custom tool, Prism might directly return the raw output of the tool's closure without necessarily making another call to the OpenAI API. 

Is there a way to configure Prism to behave this way? In other words, is it possible to have Prism return the tool's output directly as the final response, without sending it back to the language model for further processing?

**Comment by sixlive** [comment]
Not as `$response->text` but you could check for `$response->finishReason` to be `FinishReason::ToolCalls` and then get the tool call results from `$response->toolResults`.
