### ISSUE TITLE
JSON mode support

### ISSUE THREAD

**Issue by petervandijck** [echolabsdev/prism#44]
I'm using Gemini right now (I write a custom class) because of its JSON support. It would be great to build in support for JSON mode in various providers/models - it's hard to switch to prism right now without that. I understand there's a lot to do of course :)

I can pass it a schema like this:

`protected const INSIGHTS_SCHEMA = [
        'type' => 'object',
        'properties' => [
            'insights' => [
                'type' => 'array',
                'items' => [
                    'type' => 'object',
                    'properties' => [
                        'insight' => ['type' => 'string'],
                        'headline' => ['type' => 'string'],
                        'tags' => ['type' => 'string'],
                        'timeframe' => ['type' => 'string'],
                        'source' => ['type' => 'string']
                    ],
                    'required' => [
                        'insight',
                        'headline',
                        'tags',
                        'timeframe',
                        'source'
                    ]
                ]
            ]
        ],
        'required' => ['insights']
    ];`

**Comment by sixlive** [comment]
Its on the roadmap! Aside from streaming text responses its one of the next major features – [roadmap](https://prism.echolabs.dev/roadmap#mid-term-goals)
