### ISSUE TITLE
Investigate a way to expose driver specific features

### ISSUE THREAD

**Issue by sixlive** [echolabsdev/prism#5]
## Description

We need to figure out a way to expose driver specific features. For example, Anthropic [prompt caching](https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching).

## Claude Caching

This is how Vercel implemented Claude caching: https://sdk.vercel.ai/providers/ai-sdk-providers/anthropic#example-cache-control

**Comment by petervandijck** [comment]
(Not sure this is relevant but I thought I'd mention it) Can we use composition to expose underlying features? 
`return $this->api->$method(...$args);`

**Comment by sixlive** [comment]
Closing because this ticket is too open ended, will spin up a specific ticket for prompt caching
