### ISSUE TITLE
Grok text completions

### ISSUE THREAD

**Issue by eina84** [echolabsdev/prism#50]
Is it possible to use prism with xAI & Grok (not Groq)? It seems to be 'compatible' with OpenAI & Anthropic according to [the xAI documentation](https://docs.x.ai/api/integrations#openai-sdk).

```
import OpenAI from "openai";
const openai = new OpenAI({
  apiKey: "<api key>",
  baseURL: "https://api.x.ai/v1",
});

const completion = await openai.chat.completions.create({
  model: "grok-beta",
  messages: [
    { role: "system", content: "You are Grok, a chatbot inspired by the Hitchhiker's Guide to the Galaxy." },
    {
      role: "user",
      content: "What is the meaning of life, the universe, and everything?",
    },
  ],
});
```
I am confused how to do it though - I can't add another provider from the prism config file and I can't modify the existing provider to use the xAI server & API key.

**Comment by sixlive** [comment]
I'm up for this!

**Comment by pushpak1300** [comment]
Hey @eina84! To get this working, you just need to publish the config file into the designated folder. Once that’s done, you can update the OpenAI configuration as follows:

```php
'openai' => [
    'url' => env('OPENAI_URL', 'https://api.x.ai/v1'),
    'api_key' => env('OPENAI_API_KEY', '<x-api-key>'),
    'organization' => env('OPENAI_ORGANIZATION', null),
],
```

This setup should work perfectly!

Hey @sixlive! I can handle this integration, but it seems we currently lack any specific XAI features. Do you think it would be better to share OpenAI SDK functionality in a different way?

**Comment by sixlive** [comment]
I think we should just spin up an XAI provider
