### ISSUE TITLE
Ollama tools support

### ISSUE THREAD

**Issue by giancarloerra** [echolabsdev/prism#62]
Hi all, docs say that tools are not supported for Ollama...but there seem to be some related files in the source/tests. 

Is the doc outdated or they're just placeholders for a future implementation?

**Comment by pushpak1300** [comment]
@giancarloerra The tool support is avaibale for Ollama Provider. The feature which is not supported by the Ollama is [tool choice](https://prism.echolabs.dev/core-concepts/tools-function-calling.html#tool-choice-options)  which is force llm to use specific tool.

**Comment by sixlive** [comment]
Thanks @pushpak1300!

This is correct, tools are supported for Ollama, `->toolChoice` is not supported.
