### ISSUE TITLE
Nullable Schema types

### ISSUE THREAD

**Issue by studnitz** [echolabsdev/prism#69]
Hi, thanks for the awesome library!

I was testing structured outputs and found a limitation.

[Because all fields must be required in the schema](https://platform.openai.com/docs/guides/structured-outputs#all-fields-must-be-required), OpenAI recommends making the type a nullable union if one wants an "optional" field.

```diff
{
    "name": "get_weather",
    "description": "Fetches the weather in the given location",
    "strict": true,
    "parameters": {
        "type": "object",
        "properties": {
            "location": {
                "type": "string",
                "description": "The location to get the weather for"
            },
            "unit": {
+               "type": ["string", "null"],
                "description": "The unit to return the temperature in",
                "enum": ["F", "C"]
            }
        },
        "additionalProperties": false,
        "required": [
            "location", "unit"
        ]
    }
}
```

As far as I understand, this is not possible with the current Schema objects, right? Would be nice if it could be added in the future. :)

**Comment by sixlive** [comment]
Awesome, I dig this! I'll get to it soon!

**Comment by sixlive** [comment]
I think this works! Let's just call it `nullable` rather than `isNullable`."

**Comment by cosmastech** [comment]
> I think this works! Let's just call it `nullable` rather than `isNullable`."

Awesome! I should have a PR up shortly.
