### ISSUE TITLE
Responses not working with Ollama correctly

### ISSUE THREAD

**Issue by tnylea** [echolabsdev/prism#73]
Hey @sixlive, have you gotten Prism working correctly with Ollama? I have been trying to debug it this morning and will continue to try and investigate why it's not working correctly. I created a sample app where this `submit` method uses prism, like this:

```
public function submit()
{
    $response = Prism::text()
        ->using(Provider::Ollama, 'codellama')
        ->withPrompt('Tell me a short story about a brave knight.')
        ->generate();

    /*$response = Prism::text()
        ->using(Provider::Anthropic, 'claude-3-sonnet-20240229')
        ->withPrompt('Tell me a short story about a brave knight.');
        ->generate();*/

    dd($response->text);
}
```

Now, if I uncomment `anthropic` everything works fine, which is awesome!

But, when I try and use a local Ollama model. I am getting a few errrors. I was able to get a successful response by adding a `dd()` to the `EchoLabs\Prism\Providers\Ollama\Handlers\Text` class and making a few modifications, here's the modified file:

```php
<?php

declare(strict_types=1);

namespace EchoLabs\Prism\Providers\Ollama\Handlers;

use EchoLabs\Prism\Exceptions\PrismException;
use EchoLabs\Prism\Providers\Ollama\Maps\FinishReasonMap;
use EchoLabs\Prism\Providers\Ollama\Maps\MessageMap;
use EchoLabs\Prism\Providers\Ollama\Maps\ToolMap;
use EchoLabs\Prism\Providers\ProviderResponse;
use EchoLabs\Prism\Text\Request;
use EchoLabs\Prism\ValueObjects\ToolCall;
use EchoLabs\Prism\ValueObjects\Usage;
use Illuminate\Http\Client\PendingRequest;
use Illuminate\Http\Client\Response;
use Throwable;

class Text
{
    public function __construct(protected PendingRequest $client) {}

    public function handle(Request $request): ProviderResponse
    {
        try {
            $response = $this->sendRequest($request);
        } catch (Throwable $e) {
            throw PrismException::providerRequestError($request->model, $e);
        }

        $data = $response->json();

        dd($data);

        if (data_get($data, 'error') || ! $data) {
            throw PrismException::providerResponseError(vsprintf(
                'Ollama Error:  [%s] %s',
                [
                    data_get($data, 'error.type', 'unknown'),
                    data_get($data, 'error.message', 'unknown'),
                ]
            ));
        }

        return new ProviderResponse(
            text: data_get($data, 'choices.0.message.content') ?? '',
            toolCalls: $this->mapToolCalls(data_get($data, 'choices.0.message.tool_calls', []) ?? []),
            usage: new Usage(
                data_get($data, 'usage.prompt_tokens'),
                data_get($data, 'usage.completion_tokens'),
            ),
            finishReason: FinishReasonMap::map(data_get($data, 'choices.0.finish_reason', '')),
            response: [
                'id' => data_get($data, 'id'),
                'model' => data_get($data, 'model'),
            ]
        );
    }

    public function sendRequest(Request $request): Response
    {
        return $this->client->post(
            'api/chat',
            array_merge([
                'model' => $request->model,
                'messages' => [
                    [
                      "role" => "user",
                      "content" => "why is the sky blue?"
                    ]
                    ],
                'stream' => false,
                'max_tokens' => $request->maxTokens ?? 2048,
            ], array_filter([
                'temperature' => $request->temperature,
                'top_p' => $request->topP,
                'tools' => ToolMap::map($request->tools),
            ]))
        );
    }

    /**
     * @param  array<int, array<string, mixed>>  $toolCalls
     * @return array<int, ToolCall>
     */
    protected function mapToolCalls(array $toolCalls): array
    {
        return array_map(fn (array $toolCall): ToolCall => new ToolCall(
            id: data_get($toolCall, 'id'),
            name: data_get($toolCall, 'function.name'),
            arguments: data_get($toolCall, 'function.arguments'),
        ), $toolCalls);
    }
}
```

The only differences that I have done is added a `dd()` command to line `33` and then I've changed the endpoint in the `sendRequest` method from `chat/completions` to `api/chat`, which is the correct endpoint for a local Ollama installation. 

Then I hardcoded the `messages` parameter inside the `sendRequest` method to be:

```
[
    [
        "role" => "user",
        "content" => "why is the sky blue?"
    ]
]
```

> Without this hardcoded array I get an error about the structure of the message. 

Finally, I've added `'stream' => false,` to the call because Ollama streams the response by default. 

I am going to continue investigating how to resolve this and get it working correctly.

Just wanted to check if you were able to get everything working correctly with a local Ollama instance, (maybe there's something I'm doing incorrectly 🤪) LMK.

I also wanted to open this issue for a note to myself on the debugging process I've made so far, and I'll continue to keep you updated with my findings.

Really loving Prism 💎😍

**Comment by tnylea** [comment]
Awe man! Thanks for the quick response! Really appreciate it.

I guess I didn't know about the OpenAI compatibility. I was using the reference here: https://github.com/ollama/ollama/blob/main/docs/api.md on how to interact with the Ollama API.

Really appreciate the thorough explanation 👏

I think in this case, it was my end. I'll reference the OpenAI compatibility API.

Thanks again and Happy Thanksgiving 🍗🦃🍻

**Comment by sixlive** [comment]
No problem! Happy to help!

Hope you have an awesome Thanksgiving dude!

**Comment by tnylea** [comment]
@sixlive Thanks again!

I figured out my issue. I had downloaded Ollama last year sometime before the OpenAI chat completions api was available. Removing and re-installing Ollama on my end worked.

Looking forward to playing around with Prism, I was also going to see if I could help get streaming responses working on my end. If I make any progress, I'll keep you posted 😉

**Comment by sixlive** [comment]
Ahhhh that makes sense!

Appreciate the support on streaming! I had it working with Sparkle (previous project). I just need to translate it over to here. Its pretty straight forward but gets complex because we need to intercept for tool calls and tool responses + re-stream the output via Generators.
