### ISSUE TITLE
Incorrect Handling of max_tokens Parameter in o1 Model Requests

### ISSUE THREAD

**Issue by polbatllo** [echolabsdev/prism#94]
It seems that the `o1` models do not support the `max_tokens` parameter, instead relying on `max_completion_tokens`. However, the `sendRequest()` method in all Handlers currently includes a `max_tokens` value of 2048 by default for each request. Additionally, it doesn't use `array_filter` (or equivalent) to remove the parameter when explicitly set to `null`.

Should this behavior be addressed?

**Comment by polbatllo** [comment]
Some extra information:

https://platform.openai.com/docs/api-reference/completions/create

It seems max_tokens has been deprecated

**Comment by sixlive** [comment]
I'll get an update in today!

**Comment by polbatllo** [comment]
👍 !
