### ISSUE TITLE
Missing facade EchoLabs\Prism\Facades\Prism

### ISSUE THREAD

**Issue by da-mask** [echolabsdev/prism#99]
I'm not sure what I am missing but the introduction docs say I can generate a response easily with : 
```php
$response = Prism::text()
    ->using(Provider::Anthropic, 'claude-3-sonnet')
    ->withPrompt('Tell me a short story about a brave knight.')
    ->generate();
```
but the referenced `EchoLabs\Prism\Facades\Prism` appears missing ? How are the facades being referenced?

**Comment by da-mask** [comment]
Assuming I use the class directly, ie. `EchoLabs\Prism\Prism` I'll close the issue, sorry don't have time to do a PR to update the docs (assuming that is what needs to happen ? )

**Comment by sixlive** [comment]
I'll add some `use` statements to the code examples in the docs to make things more clear!

**Comment by da-mask** [comment]
Cool, and thanks for the package!
